abou us 1 & services update
front-end-by-rimantas/32-grupe-portfolio-braintech pull request #37
Opened 2022-01-02 20:27 UTC by ritullia

-  tik dalis darbo, nes tiesą sakant pastrigau. Jūsų teismui. Reikalinga komandinė pagalba :)

2022-01-03 15:04 UTC, agnekauk requested changes
Nežinau, gal Rita norėjo tarpinį variantą užkelti į develop, bet radau nemažai dalykėlių, kuriuos gerai būtų pataisyti.  😊

About us 
- trūksta šešėlių; 
- paveikslėliai labai blankūs, nors pavyzdyje ryškūs;
- užhoverinus visų spalva secondary, nors pavyzdyje visų 4 spalvos skiriasi; 
- Responsive design kol kas neveikia.  

Services
- mygtuko vieta ne ta, kokia pavyzdyje ir neveikia jo responsive;
- kaip ir about us neryškūs paveikslėliai, neatitinka hoveris;
- responsive neatitinka lyginant su pavyzdžiu;
- nėra plonų vertikalių baltų linijų, kurios yra pavyzdyje (jomis juda animacija, tai gal galima palikti vėlesnei užduočiai, kai bus daromos animacijos).

2022-01-04 16:44 UTC, agnekauk submitted a review, later dismissed

2022-01-04 18:23 UTC, nsn1930 submitted a review, later dismissed

2022-01-04 19:08 UTC, agnekauk submitted a review, later dismissed

2022-01-05 17:21 UTC, closed without merging