Lets talk section
front-end-by-rimantas/32-grupe-portfolio-braintech pull request #52
Opened 2022-01-08 16:21 UTC by VaidasUrb

2022-01-09 08:52 UTC, brokenfingers requested changes, later dismissed
trūksta uždarančio skliausto, home.css 749 eilutė

2022-01-09 08:52 UTC, brokenfingers commented on css/pages/home.css
> +
trūksta uždarančio skliausto

2022-01-28 22:14 UTC, belauzas commented on css/pages/home.css
> +
Fixed

2022-01-28 22:26 UTC, belauzas approved these changes
Kas labai blogai, tai jog pirminiame variante buvo sumaišyta `.container`, `.row` ir `.col-[x]` naudojimas. Kai jie apsirašo, jų stilių **nereikia** perrašinėti, nes tai viską ir griovė... Kiek galėjau - pataisiau.

2022-01-28 22:26 UTC, merged