Service section grid
front-end-by-rimantas/32-grupe-portfolio-braintech pull request #53
Opened 2022-01-11 15:22 UTC by ritullia

- Pakeista servises sekcija su grid
- Sutvarkytas SERVICES sekcijos ir button responsive 
- About sekcijoje pakitimai (bus kitas branchas ir užduotis)

2022-01-12 23:00 UTC, brokenfingers requested changes
negaliu aprovint, nes pakeitimai sugriovė "about us" sekciją. jeigu uzduotis yra "Service section" tada ir keičiam service section, o jei kazką darom "about us" sekcijoje tada ir kuriam pr butent šiai sekcijai.

2022-01-13 06:35 UTC, ritullia commented
keičiau Servises section, ne About us pirmą sekciją. Jai yra sukurtas atskiras branch'as, nes joje reikalingi kiti selector'iai. Todėl dabar ji ir atrodo sugriuvusi. Projekte issues atnaujintos užduotys, kiekviena atskirai.

2022-01-30 11:50 UTC, ritullia reviewed
Services sekcijoje atlikti pakeitimai ir sutvarkyta pagal grid, sutvarkytas responsive designe.

2022-02-01 13:30 UTC, brokenfingers commented
reikia padaryti update iš develop'o ir sutikrint ar nera konfliktu

2022-02-02 20:44 UTC, ritullia reviewed
is develop prie darant pull requests padariau branch update del konfliktu, man nemete ir dabar dar patikrinau, nera.  🧐

2022-02-03 21:14 UTC, brokenfingers approved these changes
suklydau del konfliktų, pas mane buvo kažkokie lokaliai daryti pakeitimai ant šito brancho :))

2022-02-03 21:14 UTC, merged